### ISSUE TITLE
Any date for a first version of this kernel?

### ISSUE THREAD

**Issue by josepsx** [bq/aquaris-U#1]
Saludos.
¿Tenéis alguna fecha para la primera versión de este kernel?.

---

Hi.
You have any date for the first version of this kernel?

**Comment by jbruechert** [comment]
Have a look at the already released versions, you find them as "tags": https://github.com/bq/aquaris-U/tree/1.3.0_20161017-1036

**Comment by Kra1o5** [comment]
Hello @josepsx,

As @JBBgameich told you, you can check all releases here: https://github.com/bq/aquaris-U/releases

Greetings
