### ISSUE TITLE
How good is the device supported?

### ISSUE THREAD

**Issue by jbruechert** [bq/aquaris-U#2]
I am a bit confused about the wlan module being in a extra repository, and when building this kernel it warns me about it a missing sound module. So my question is how complete this sources are? Are that the sources from which the official kernel releases are built, or just a repository containing the GPL stuff for legal reasons?

**Comment by Kra1o5** [comment]
Hi @JBBgameich,

Kernel and Wlan sources are complete, compile and work correctly.

You can find the instructions here:

**Kernel:** https://github.com/bq/aquaris-U/blob/aquaris-U/README.md
**Wlan:** https://github.com/bq/wlan_module_qcom/blob/aquaris-U/README.md

If you have any questions about the compilation process you can contact us at opensource@bq.com

Regards,
